<?php

namespace common\onecms;

use common\models\Advertising;
use yii\base\Widget;

class AdsRightTopWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $nodes = Advertising::findOne(['position' => 'right_top']);
        return $this->render('AdsRightTopWidget', [
            'nodes' => $nodes,
        ]);
    }
}