<?php

namespace common\onecms;

use common\models\Advertising;
use yii\base\Widget;

class AdsTopCenterRightWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $nodes = Advertising::find()->where(['position' => 'top_center_right', 'status' => 10])->all();
        return $this->render('AdsTopCenterRightWidget', [
            'nodes' => $nodes,
        ]);
    }
}