<?php

namespace common\onecms;

use common\models\Post;
use yii\base\Widget;

class FrontPostWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $nodes = Post::find()->where(['status' => 10])->limit(4)->all();
        return $this->render('FrontPostWidget', [
            'nodes' => $nodes,
        ]);
    }
}