<?php

namespace common\onecms;

use common\models\Product;
use yii\base\Widget;

class FrontProductWidget extends Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $nodes = Product::find()->where(['status' => 10])->limit(12)->all();
        return $this->render('FrontProductWidget', [
            'nodes' => $nodes,
        ]);
    }
}