<?php

namespace common\onecms;

use common\models\Product;
use yii\base\Widget;

class ProductBottomTopWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $nodes = Product::find()->where(['status' => 10])->limit(3)->all();
        return $this->render('ProductBottomTopWidget', [
            'nodes' => $nodes,
        ]);
    }
}