<?php

namespace common\onecms;

use common\models\Post;
use common\models\PostCategory;
use yii\base\Widget;

class RelatedPostWidget extends Widget
{
    public $category_id;
    public $node_id;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $categoriesData = PostCategory::findOne($this->category_id)->leaves()->all();
        $categories = array();
        $categories[] = $this->category_id;
        if($categoriesData) {
            foreach($categoriesData as $category) {
                $categories[] = $category->id;
            }
        }
        $offset = Post::find()->where(['in', 'category_id', $categories])
            ->andWhere(['>', 'id', $this->node_id])
            ->andFilterWhere(['status' => 10])
            ->orderBy(['id' => SORT_DESC])->count();
        $nodes = Post::find()->where(['in', 'category_id', $categories])
            ->andFilterWhere(['status' => 10])->orderBy(['id' => SORT_DESC])->limit(4)->offset($offset)->all();
        return $this->render('RelatedPostWidget', [
            'nodes' => $nodes,
        ]);
    }
}