<?php

namespace common\onecms;

use common\models\Video;
use yii\base\Widget;

class VideoRightWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $nodes = Video::find()->where(['status' => 10])->limit(2)->all();
        return $this->render('VideoRightWidget', [
            'nodes' => $nodes,
        ]);
    }
}