<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Bạn có chắc chắn muốn xóa mục này?',
    'Catalogue Categories' => 'Danh mục Tạp chí',
    'Catalogues' => 'Tạp chí',
    'Category ID' => 'Danh mục',
    'Company ID' => 'Công ty',
    'Content' => 'Nội dung',
    'Create Catalogue' => 'Thêm mới',
    'Create Catalogue Category' => 'Thêm mới',
    'Create Event' => 'Thêm mới',
    'Create Event Category' => 'Thêm mới',
    'Create Gallery' => 'Thêm mới',
    'Create Gallery Category' => 'Thêm mới',
    'Create Page' => 'Thêm mới',
    'Create Post' => 'Thêm mới',
    'Create Post Category' => 'Thêm mới',
    'Create Product' => 'Thêm mới',
    'Create Product Category' => 'Thêm mới',
    'Create Product Company' => 'Thêm mới',
    'Create Review' => 'Thêm mới',
    'Create Review Category' => 'Thêm mới',
    'Create Video' => 'Thêm mới',
    'Create Video Category' => 'Thêm mới',
    'Created At' => '',
    'Created By' => '',
    'Delete' => 'Xóa',
    'Depth' => '',
    'Description' => 'Nội dung',
    'Download' => 'Tải về',
    'End Date' => 'Ngày kết thúc',
    'Event Categories' => 'Danh mục Sự kiện',
    'Events' => 'Sự kiện',
    'Galleries' => 'Thư viện ảnh',
    'Gallery' => 'Thư viện ảnh',
    'Gallery Categories' => 'Danh mục thư viện ảnh',
    'ID' => '',
    'Image' => 'Hình ảnh',
    'Lft' => '',
    'Location' => 'Địa điểm',
    'Meta Description' => 'SEO - Mô tả',
    'Meta Keywords' => 'SEO - Từ khóa',
    'Meta Title' => 'SEO - Tiêu đề',
    'Pages' => 'Trang cố định',
    'Parent ID' => 'Danh mục cha',
    'Post Categories' => 'Danh mục',
    'Posts' => 'Bài viết',
    'Price' => 'Giá sản phẩm',
    'Product Categories' => 'Danh mục',
    'Product Companies' => 'Danh mục',
    'Products' => 'Sản phẩm',
    'Reset' => '',
    'Review Categories' => 'Danh mục',
    'Reviews' => 'Đánh giá',
    'Rgt' => '',
    'Search' => '',
    'Sku' => '',
    'Slug' => 'Đường dẫn thân thiện',
    'Start Date' => '',
    'Status' => 'Trạng thái',
    'Title' => 'Tiêu đề',
    'Update' => 'Cập nhật',
    'Update title' => 'Cập nhật nội dung',
    'Update {modelClass}: ' => 'Cập nhật nội dung',
    'Updated At' => '',
    'Updated By' => '',
    'Video Categories' => 'Danh mục',
    'Videos' => '',
    'Youtube ID' => '',
    'Create' => 'Thêm mới',
];
